# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaSegunda(object):
    def setupUi(self, janelaSegunda):
        janelaSegunda.setObjectName("janelaSegunda")
        janelaSegunda.setEnabled(True)
        janelaSegunda.resize(646, 519)
        font = QtGui.QFont()
        font.setKerning(True)
        janelaSegunda.setFont(font)
        janelaSegunda.setAccessibleDescription("")
        janelaSegunda.setStyleSheet("background-color: rgb(242, 144, 255);")
        self.centralwidget = QtWidgets.QWidget(janelaSegunda)
        self.centralwidget.setObjectName("centralwidget")
        self.botaoVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoVoltar.setGeometry(QtCore.QRect(130, 360, 131, 51))
        self.botaoVoltar.setStyleSheet("color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 0, 0);")
        self.botaoVoltar.setObjectName("botaoVoltar")
        self.botaoConcluir = QtWidgets.QPushButton(self.centralwidget)
        self.botaoConcluir.setGeometry(QtCore.QRect(350, 360, 131, 51))
        self.botaoConcluir.setStyleSheet("color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 0, 0);")
        self.botaoConcluir.setObjectName("botaoConcluir")
        self.inputCidade = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCidade.setGeometry(QtCore.QRect(120, 221, 151, 31))
        self.inputCidade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputCidade.setObjectName("inputCidade")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 62, 561, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_rua = QtWidgets.QLabel(self.centralwidget)
        self.label_rua.setGeometry(QtCore.QRect(40, 110, 55, 21))
        self.label_rua.setObjectName("label_rua")
        self.label_numero = QtWidgets.QLabel(self.centralwidget)
        self.label_numero.setGeometry(QtCore.QRect(490, 100, 91, 41))
        self.label_numero.setObjectName("label_numero")
        self.label_endereco = QtWidgets.QLabel(self.centralwidget)
        self.label_endereco.setGeometry(QtCore.QRect(40, 20, 151, 51))
        self.label_endereco.setObjectName("label_endereco")
        self.inputCep = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCep.setGeometry(QtCore.QRect(90, 160, 131, 31))
        self.inputCep.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputCep.setObjectName("inputCep")
        self.label_cidade_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_cidade_2.setGeometry(QtCore.QRect(40, 221, 81, 31))
        self.label_cidade_2.setObjectName("label_cidade_2")
        self.inputNr = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNr.setGeometry(QtCore.QRect(530, 110, 71, 31))
        self.inputNr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputNr.setObjectName("inputNr")
        self.label_CEP = QtWidgets.QLabel(self.centralwidget)
        self.label_CEP.setGeometry(QtCore.QRect(40, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_CEP.setFont(font)
        self.label_CEP.setObjectName("label_CEP")
        self.inputcomboBoxEstado = QtWidgets.QComboBox(self.centralwidget)
        self.inputcomboBoxEstado.setGeometry(QtCore.QRect(410, 220, 101, 31))
        self.inputcomboBoxEstado.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputcomboBoxEstado.setObjectName("inputcomboBoxEstado")
        self.inputcomboBoxEstado.addItem("")
        self.inputcomboBoxEstado.addItem("")
        self.inputcomboBoxEstado.addItem("")
        self.inputcomboBoxEstado.addItem("")
        self.inputcomboBoxEstado.addItem("")
        self.inputcomboBoxEstado.addItem("")
        self.label_estado_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_estado_2.setGeometry(QtCore.QRect(340, 220, 71, 31))
        self.label_estado_2.setObjectName("label_estado_2")
        self.inputRua = QtWidgets.QLineEdit(self.centralwidget)
        self.inputRua.setGeometry(QtCore.QRect(90, 110, 371, 31))
        self.inputRua.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputRua.setObjectName("inputRua")
        self.label_CEP_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_CEP_2.setGeometry(QtCore.QRect(280, 170, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_CEP_2.setFont(font)
        self.label_CEP_2.setObjectName("label_CEP_2")
        self.inputBairro = QtWidgets.QLineEdit(self.centralwidget)
        self.inputBairro.setGeometry(QtCore.QRect(350, 160, 251, 31))
        self.inputBairro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputBairro.setObjectName("inputBairro")
        janelaSegunda.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(janelaSegunda)
        self.statusbar.setObjectName("statusbar")
        janelaSegunda.setStatusBar(self.statusbar)

        self.retranslateUi(janelaSegunda)
        QtCore.QMetaObject.connectSlotsByName(janelaSegunda)

    def retranslateUi(self, janelaSegunda):
        _translate = QtCore.QCoreApplication.translate
        janelaSegunda.setWindowTitle(_translate("janelaSegunda", "Cadastro - Outras informações"))
        self.botaoVoltar.setText(_translate("janelaSegunda", "Voltar"))
        self.botaoConcluir.setText(_translate("janelaSegunda", "Concluir"))
        self.label_rua.setText(_translate("janelaSegunda", "<html><head/><body><p><span style=\" font-size:12pt;\">Rua:</span></p></body></html>"))
        self.label_numero.setText(_translate("janelaSegunda", "<html><head/><body><p><span style=\" font-size:12pt;\">Nr:</span></p></body></html>"))
        self.label_endereco.setText(_translate("janelaSegunda", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Endereço</span></p></body></html>"))
        self.label_cidade_2.setText(_translate("janelaSegunda", "<html><head/><body><p><span style=\" font-size:12pt;\">Cidade:</span></p></body></html>"))
        self.label_CEP.setText(_translate("janelaSegunda", "CEP:"))
        self.inputcomboBoxEstado.setItemText(0, _translate("janelaSegunda", "Selecione"))
        self.inputcomboBoxEstado.setItemText(1, _translate("janelaSegunda", "MS"))
        self.inputcomboBoxEstado.setItemText(2, _translate("janelaSegunda", "MT"))
        self.inputcomboBoxEstado.setItemText(3, _translate("janelaSegunda", "SP"))
        self.inputcomboBoxEstado.setItemText(4, _translate("janelaSegunda", "GO"))
        self.inputcomboBoxEstado.setItemText(5, _translate("janelaSegunda", "RS"))
        self.label_estado_2.setText(_translate("janelaSegunda", "<html><head/><body><p><span style=\" font-size:12pt;\">Estado:</span></p></body></html>"))
        self.label_CEP_2.setText(_translate("janelaSegunda", "Bairro:"))
