# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaPrimeira(object):
    
    ##def __init__(self,nome):
    #    self.x=nome
    
    def getNome(self):
        return self.x
        
    def setNome(self,nome):
        self.x = nome
    
    def setupUi(self, janelaPrimeira):
        janelaPrimeira.setObjectName("janelaPrimeira")
        janelaPrimeira.resize(650, 614)
        janelaPrimeira.setStyleSheet("background-color: rgb(242, 144, 255);")
        self.centralwidget = QtWidgets.QWidget(janelaPrimeira)
        self.centralwidget.setObjectName("centralwidget")
        self.botaoEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoEnviar.setGeometry(QtCore.QRect(130, 490, 131, 51))
        self.botaoEnviar.setStyleSheet("color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 0, 0);")
        self.botaoEnviar.setObjectName("botaoEnviar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 251, 41))
        self.label.setObjectName("label")
        self.inputNome = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNome.setGeometry(QtCore.QRect(120, 120, 491, 31))
        self.inputNome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputNome.setObjectName("inputNome")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 81, 31))
        self.label_3.setObjectName("label_3")
        self.inputRg = QtWidgets.QLineEdit(self.centralwidget)
        self.inputRg.setGeometry(QtCore.QRect(120, 180, 491, 31))
        self.inputRg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputRg.setObjectName("inputRg")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 81, 31))
        self.label_4.setObjectName("label_4")
        self.inputEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEmail.setGeometry(QtCore.QRect(120, 240, 491, 31))
        self.inputEmail.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputEmail.setObjectName("inputEmail")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 304, 121, 31))
        self.label_5.setObjectName("label_5")
        self.botaoCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoCancelar.setGeometry(QtCore.QRect(380, 490, 131, 51))
        self.botaoCancelar.setStyleSheet("color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 0, 0);")
        self.botaoCancelar.setObjectName("botaoCancelar")
        self.radioButtonSuperior = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonSuperior.setGeometry(QtCore.QRect(180, 309, 101, 21))
        self.radioButtonSuperior.setObjectName("radioButtonSuperior")
        self.radioButtonMedio = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonMedio.setGeometry(QtCore.QRect(294, 310, 101, 21))
        self.radioButtonMedio.setObjectName("radioButtonMedio")
        self.radioButtonFundamental = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFundamental.setGeometry(QtCore.QRect(400, 310, 101, 21))
        self.radioButtonFundamental.setObjectName("radioButtonFundamental")
        self.dataFormacao = QtWidgets.QDateEdit(self.centralwidget)
        self.dataFormacao.setGeometry(QtCore.QRect(218, 366, 110, 22))
        self.dataFormacao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dataFormacao.setObjectName("dataFormacao")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 360, 161, 31))
        self.label_6.setObjectName("label_6")
        janelaPrimeira.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(janelaPrimeira)
        self.statusbar.setObjectName("statusbar")
        janelaPrimeira.setStatusBar(self.statusbar)

        self.retranslateUi(janelaPrimeira)
        self.botaoCancelar.clicked.connect(janelaPrimeira.close)
        QtCore.QMetaObject.connectSlotsByName(janelaPrimeira)
        

    def retranslateUi(self, janelaPrimeira):
        _translate = QtCore.QCoreApplication.translate
        janelaPrimeira.setWindowTitle(_translate("janelaPrimeira", "Cadastro - Informações Pessoais"))
        self.botaoEnviar.setText(_translate("janelaPrimeira", "Próximo"))
        self.label.setText(_translate("janelaPrimeira", "<html><head/><body><p><span style=\" font-size:12pt;\">Informações Pessoais:</span></p></body></html>"))
        self.label_2.setText(_translate("janelaPrimeira", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Nome:</span></p></body></html>"))
        self.label_3.setText(_translate("janelaPrimeira", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">RG:</span></p></body></html>"))
        self.label_4.setText(_translate("janelaPrimeira", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">E-mail:</span></p></body></html>"))
        self.label_5.setText(_translate("janelaPrimeira", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Escolaridade:</span></p></body></html>"))
        self.botaoCancelar.setText(_translate("janelaPrimeira", "Cancelar"))
        self.radioButtonSuperior.setText(_translate("janelaPrimeira", "Superior"))
        self.radioButtonMedio.setText(_translate("janelaPrimeira", "Médio"))
        self.radioButtonFundamental.setText(_translate("janelaPrimeira", "Fundamental"))
        self.label_6.setText(_translate("janelaPrimeira", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Data de formação:</span></p></body></html>"))
        
